### ISSUE TITLE
Update for 2.4.1 release

### ISSUE THREAD

**Issue by Chilledheart** [rui314/setup-mold#14]
New 2.4.1 release is out but the default version of setup-mold is still 2.4.0

https://github.com/rui314/mold/releases/tag/v2.4.1

**Comment by rui314** [comment]
It's automated now. GitHub Action in this repo will update the file one week after each release.

**Comment by rui314** [comment]
If you want to use 2.4.1 right now, you can add `mold-version: 2.4.1` in your YAML file. I don't want to make it default immediately to stay on a safer side.
