### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by starwolfy** [rui314/setup-mold#3]
Tried this on the CI setup of my Github repository but it doesn't seem to improve the compilation speed.

Does this action create a `config.toml` pointing to this linker by default? If not it would be useful if it did for Rust repositories!

**Comment by rui314** [comment]
It replaces the linker at the default path (`/usr/bin/ld`), so the effect should be global.

What is your program? Can I see your GitHub Actions logs?

**Comment by starwolfy** [comment]
After re-examination, I realized this action did actually work. Turns out this is an invalid issue and I apologize for that.

My project compiles modules from a game engine (Bevy ECS).

Without setup-mold:
https://github.com/starwolves/space/runs/6083707375?check_suite_focus=true

With setup-mold:
https://github.com/starwolves/space/runs/6083253856?check_suite_focus=true

There is a clear two-minute gain in compilation time!!!

**Comment by rui314** [comment]
Nice! Glad to hear that mold worked for you.
